/**
 * Centralized Vocabulary Data for Linguo
 * Contains categorized terms, IPA phonetics, chunks, and examples for English (en) and Spanish (es)
 */
(function(global) {
  const VOCABULARY_DATA = {
    en: [
      {
            "id": "en_apple",
            "type": "word",
            "icon": "🍎",
            "term": "apple",
            "ipa": "/ˈæp.əl/",
            "pos": "Substantivo",
            "translation": "maçã",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "I eat a fresh apple every morning.",
            "examplePt": "Eu como uma maçã fresca toda manhã."
      },
      {
            "id": "en_bread",
            "type": "word",
            "icon": "🍞",
            "term": "bread",
            "ipa": "/brɛd/",
            "pos": "Substantivo",
            "translation": "pão",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "Do you like fresh bread with butter?",
            "examplePt": "Você gosta de pão fresco com manteiga?"
      },
      {
            "id": "en_coffee",
            "type": "word",
            "icon": "☕",
            "term": "coffee",
            "ipa": "/ˈkɒf.i/",
            "pos": "Substantivo",
            "translation": "café",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "Can I have a cup of black coffee, please?",
            "examplePt": "Pode me trazer uma xícara de café preto, por favor?"
      },
      {
            "id": "en_water",
            "type": "word",
            "icon": "💧",
            "term": "water",
            "ipa": "/ˈwɔː.tər/",
            "pos": "Substantivo",
            "translation": "água",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "Drink plenty of water on hot days.",
            "examplePt": "Beba bastante água em dias quentes."
      },
      {
            "id": "en_sparkling_water",
            "type": "chunk",
            "icon": "🫧",
            "term": "sparkling water",
            "ipa": "/ˈspɑːr.klɪŋ ˈwɔː.tər/",
            "pos": "Expressão",
            "translation": "água com gás",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "Would you like still or sparkling water with your meal?",
            "examplePt": "Você prefere água sem gás ou com gás com sua refeição?"
      },
      {
            "id": "en_order_the_check",
            "type": "chunk",
            "icon": "🧾",
            "term": "order the check",
            "ipa": "/ˈɔːr.dər ðə tʃɛk/",
            "pos": "Expressão",
            "translation": "pedir a conta",
            "category": "Alimentos & Bebidas",
            "level": "A2",
            "example": "Excuse me, can we order the check, please?",
            "examplePt": "Com licença, podemos pedir a conta, por favor?"
      },
      {
            "id": "en_on_the_house",
            "type": "chunk",
            "icon": "🎁",
            "term": "on the house",
            "ipa": "/ɒn ðə haʊs/",
            "pos": "Expressão",
            "translation": "cortesia da casa (grátis)",
            "category": "Alimentos & Bebidas",
            "level": "B1",
            "example": "Don't worry about the dessert, it's on the house!",
            "examplePt": "Não se preocupe com a sobremesa, é cortesia da casa!"
      },
      {
            "id": "en_split_the_bill",
            "type": "chunk",
            "icon": "💳",
            "term": "split the bill",
            "ipa": "/splɪt ðə bɪl/",
            "pos": "Expressão",
            "translation": "dividir a conta",
            "category": "Alimentos & Bebidas",
            "level": "A2",
            "example": "We had dinner together and decided to split the bill.",
            "examplePt": "Jantamos juntos e decidimos dividir a conta."
      },
      {
            "id": "en_airport",
            "type": "word",
            "icon": "✈️",
            "term": "airport",
            "ipa": "/ˈɛər.pɔːrt/",
            "pos": "Substantivo",
            "translation": "aeroporto",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "We need to arrive at the airport two hours early.",
            "examplePt": "Precisamos chegar ao aeroporto duas horas mais cedo."
      },
      {
            "id": "en_passport",
            "type": "word",
            "icon": "🛂",
            "term": "passport",
            "ipa": "/ˈpæs.pɔːrt/",
            "pos": "Substantivo",
            "translation": "passaporte",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "Always keep your passport in a safe place.",
            "examplePt": "Sempre guarde seu passaporte em um lugar seguro."
      },
      {
            "id": "en_suitcase",
            "type": "word",
            "icon": "🧳",
            "term": "suitcase",
            "ipa": "/ˈsuːt.keɪs/",
            "pos": "Substantivo",
            "translation": "mala de viagem",
            "category": "Viagem & Cidade",
            "level": "A2",
            "example": "My suitcase is packed and ready for the trip.",
            "examplePt": "Minha mala está pronta para a viagem."
      },
      {
            "id": "en_subway",
            "type": "word",
            "icon": "🚇",
            "term": "subway",
            "ipa": "/ˈsʌb.weɪ/",
            "pos": "Substantivo",
            "translation": "metrô",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "Taking the subway is the fastest way to travel in NYC.",
            "examplePt": "Pegar o metrô é a forma mais rápida de se locomover em NY."
      },
      {
            "id": "en_boarding_pass",
            "type": "chunk",
            "icon": "🎫",
            "term": "boarding pass",
            "ipa": "/ˈbɔːr.dɪŋ pæs/",
            "pos": "Expressão",
            "translation": "cartão de embarque",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "Please show your boarding pass at the gate.",
            "examplePt": "Por favor, mostre seu cartão de embarque no portão."
      },
      {
            "id": "en_carry_on_luggage",
            "type": "chunk",
            "icon": "🎒",
            "term": "carry-on luggage",
            "ipa": "/ˈkæri ɒn ˈlʌɡɪdʒ/",
            "pos": "Expressão",
            "translation": "bagagem de mão",
            "category": "Viagem & Cidade",
            "level": "A2",
            "example": "You can bring one piece of carry-on luggage onto the plane.",
            "examplePt": "Você pode levar uma mala de mão no avião."
      },
      {
            "id": "en_catch_a_flight",
            "type": "chunk",
            "icon": "🛫",
            "term": "catch a flight",
            "ipa": "/kætʃ ə flaɪt/",
            "pos": "Expressão",
            "translation": "pegar um voo",
            "category": "Viagem & Cidade",
            "level": "A2",
            "example": "We have to leave now to catch our morning flight.",
            "examplePt": "Temos que sair agora para pegar o nosso voo da manhã."
      },
      {
            "id": "en_layover",
            "type": "word",
            "icon": "⏱️",
            "term": "layover",
            "ipa": "/ˈleɪˌoʊ.vər/",
            "pos": "Substantivo",
            "translation": "escala / conexão de voo",
            "category": "Viagem & Cidade",
            "level": "B1",
            "example": "We have a two-hour layover in Atlanta before flying home.",
            "examplePt": "Temos uma escala de duas horas em Atlanta antes de voar para casa."
      },
      {
            "id": "en_customs",
            "type": "word",
            "icon": "👮",
            "term": "customs",
            "ipa": "/ˈkʌs.təmz/",
            "pos": "Substantivo",
            "translation": "alfândega",
            "category": "Viagem & Cidade",
            "level": "B1",
            "example": "It took only ten minutes to go through customs.",
            "examplePt": "Levou apenas dez minutos para passar pela alfândega."
      },
      {
            "id": "en_meeting",
            "type": "word",
            "icon": "💼",
            "term": "meeting",
            "ipa": "/ˈmiː.tɪŋ/",
            "pos": "Substantivo",
            "translation": "reunião",
            "category": "Trabalho & Rotina",
            "level": "A1",
            "example": "I have an important team meeting at 10 AM.",
            "examplePt": "Tenho uma reunião importante de equipe às 10h."
      },
      {
            "id": "en_deadline",
            "type": "word",
            "icon": "⏳",
            "term": "deadline",
            "ipa": "/ˈdɛd.laɪn/",
            "pos": "Substantivo",
            "translation": "prazo limite",
            "category": "Trabalho & Rotina",
            "level": "A2",
            "example": "Friday is the strict deadline for this project.",
            "examplePt": "Sexta-feira é o prazo final rigoroso para este projeto."
      },
      {
            "id": "en_take_a_break",
            "type": "chunk",
            "icon": "☕",
            "term": "take a break",
            "ipa": "/teɪk ə breɪk/",
            "pos": "Expressão",
            "translation": "fazer uma pausa",
            "category": "Trabalho & Rotina",
            "level": "A1",
            "example": "You have worked for three hours; take a break.",
            "examplePt": "Você trabalhou por três horas; faça uma pausa."
      },
      {
            "id": "en_meet_a_deadline",
            "type": "chunk",
            "icon": "🎯",
            "term": "meet a deadline",
            "ipa": "/miːt ə ˈdɛdlaɪn/",
            "pos": "Expressão",
            "translation": "cumprir um prazo",
            "category": "Trabalho & Rotina",
            "level": "B1",
            "example": "Our team worked late yesterday to meet the tight deadline.",
            "examplePt": "Nossa equipe trabalhou até tarde ontem para cumprir o prazo apertado."
      },
      {
            "id": "en_touch_base",
            "type": "chunk",
            "icon": "🤝",
            "term": "touch base",
            "ipa": "/tʌtʃ beɪs/",
            "pos": "Expressão",
            "translation": "alinhar rapidamente / conversar",
            "category": "Trabalho & Rotina",
            "level": "B1",
            "example": "Let's touch base next Monday to review the status.",
            "examplePt": "Vamos nos alinhar na próxima segunda para revisar o status."
      },
      {
            "id": "en_work_overtime",
            "type": "chunk",
            "icon": "⏰",
            "term": "work overtime",
            "ipa": "/wɜːrk ˈoʊvərˌtaɪm/",
            "pos": "Expressão",
            "translation": "fazer hora extra",
            "category": "Trabalho & Rotina",
            "level": "A2",
            "example": "She had to work overtime to finish the report.",
            "examplePt": "Ela teve que fazer hora extra para terminar o relatório."
      },
      {
            "id": "en_call_in_sick",
            "type": "chunk",
            "icon": "🤒",
            "term": "call in sick",
            "ipa": "/kɔːl ɪn sɪk/",
            "pos": "Expressão",
            "translation": "ligar avisando ausência por doença",
            "category": "Trabalho & Rotina",
            "level": "B1",
            "example": "Sarah had the flu and had to call in sick today.",
            "examplePt": "Sarah estava gripada e teve que avisar que não iria hoje."
      },
      {
            "id": "en_key",
            "type": "word",
            "icon": "🔑",
            "term": "key",
            "ipa": "/kiː/",
            "pos": "Substantivo",
            "translation": "chave",
            "category": "Cotidiano & Objetos",
            "level": "A1",
            "example": "Don't forget to take your house key with you.",
            "examplePt": "Não esqueça de levar a chave de casa com você."
      },
      {
            "id": "en_wallet",
            "type": "word",
            "icon": "👛",
            "term": "wallet",
            "ipa": "/ˈwɒl.ɪt/",
            "pos": "Substantivo",
            "translation": "carteira",
            "category": "Cotidiano & Objetos",
            "level": "A1",
            "example": "I left my wallet in the car by accident.",
            "examplePt": "Deixei minha carteira no carro por acidente."
      },
      {
            "id": "en_get_ready",
            "type": "chunk",
            "icon": "👔",
            "term": "get ready",
            "ipa": "/ɡɛt ˈrɛd.i/",
            "pos": "Expressão",
            "translation": "se arrumar / se aprontar",
            "category": "Cotidiano & Objetos",
            "level": "A1",
            "example": "It takes me twenty minutes to get ready in the morning.",
            "examplePt": "Levo vinte minutos para me arrumar pela manhã."
      },
      {
            "id": "en_wake_up_early",
            "type": "chunk",
            "icon": "🌅",
            "term": "wake up early",
            "ipa": "/weɪk ʌp ˈɜːr.li/",
            "pos": "Expressão",
            "translation": "acordar cedo",
            "category": "Cotidiano & Objetos",
            "level": "A1",
            "example": "I always wake up early on weekdays to go for a run.",
            "examplePt": "Eu sempre acordo cedo nos dias de semana para correr."
      },
      {
            "id": "en_run_errands",
            "type": "chunk",
            "icon": "🛒",
            "term": "run errands",
            "ipa": "/rʌn ˈɛr.əndz/",
            "pos": "Expressão",
            "translation": "resolver tarefas de rua",
            "category": "Cotidiano & Objetos",
            "level": "B1",
            "example": "I spent the whole Saturday morning running errands.",
            "examplePt": "Passei toda a manhã de sábado resolvendo coisas na rua."
      },
      {
            "id": "en_hit_the_gym",
            "type": "chunk",
            "icon": "🏋️",
            "term": "hit the gym",
            "ipa": "/hɪt ðə dʒɪm/",
            "pos": "Expressão",
            "translation": "ir malhar / ir à academia",
            "category": "Cotidiano & Objetos",
            "level": "A2",
            "example": "I usually hit the gym three times a week.",
            "examplePt": "Eu costumo ir à academia três vezes por semana."
      },
      {
            "id": "en_choose",
            "type": "word",
            "icon": "🎯",
            "term": "choose",
            "ipa": "/tʃuːz/",
            "pos": "Verbo",
            "translation": "escolher",
            "category": "Ações Essenciais / Verbos",
            "level": "A1",
            "example": "You can choose any book you want from the shelf.",
            "examplePt": "Você pode escolher qualquer livro que quiser da estante."
      },
      {
            "id": "en_decide",
            "type": "word",
            "icon": "💡",
            "term": "decide",
            "ipa": "/dɪˈsaɪd/",
            "pos": "Verbo",
            "translation": "decidir",
            "category": "Ações Essenciais / Verbos",
            "level": "A2",
            "example": "Take your time to decide what is best for you.",
            "examplePt": "Tome seu tempo para decidir o que é melhor para você."
      },
      {
            "id": "en_figure_out",
            "type": "chunk",
            "icon": "🧩",
            "term": "figure out",
            "ipa": "/ˈfɪɡ.jər aʊt/",
            "pos": "Expressão",
            "translation": "descobrir / compreender / resolver",
            "category": "Ações Essenciais / Verbos",
            "level": "B1",
            "example": "Don't worry, we will figure out how to solve this bug.",
            "examplePt": "Não se preocupe, vamos descobrir como resolver este problema."
      },
      {
            "id": "en_look_forward_to",
            "type": "chunk",
            "icon": "🤩",
            "term": "look forward to",
            "ipa": "/lʊk ˈfɔːr.wərd tuː/",
            "pos": "Expressão",
            "translation": "aguardar com grande expectativa",
            "category": "Ações Essenciais / Verbos",
            "level": "B1",
            "example": "I look forward to meeting your family this weekend.",
            "examplePt": "Estou ansioso para conhecer sua família neste fim de semana."
      },
      {
            "id": "en_give_up",
            "type": "chunk",
            "icon": "🏳️",
            "term": "give up",
            "ipa": "/ɡɪv ʌp/",
            "pos": "Expressão",
            "translation": "desistir / abrir mão",
            "category": "Ações Essenciais / Verbos",
            "level": "A2",
            "example": "Learning English takes patience, so never give up!",
            "examplePt": "Aprender inglês exige paciência, então nunca desista!"
      },
      {
            "id": "en_run_out_of",
            "type": "chunk",
            "icon": "⌛",
            "term": "run out of",
            "ipa": "/rʌn aʊt əv/",
            "pos": "Expressão",
            "translation": "ficar sem / esgotar",
            "category": "Ações Essenciais / Verbos",
            "level": "A2",
            "example": "Hurry up! We are running out of time before the gate closes.",
            "examplePt": "Depressa! Estamos ficando sem tempo antes que o portão feche."
      },
      {
            "id": "en_actually",
            "type": "word",
            "icon": "💬",
            "term": "actually",
            "ipa": "/ˈæk.tʃu.ə.li/",
            "pos": "Advérbio",
            "translation": "na verdade / na realidade",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "A2",
            "example": "I thought he was British, but actually he is Australian.",
            "examplePt": "Pensei que ele fosse britânico, mas na verdade ele é australiano."
      },
      {
            "id": "en_push",
            "type": "word",
            "icon": "🚪",
            "term": "push",
            "ipa": "/pʊʃ/",
            "pos": "Verbo",
            "translation": "empurrar (não puxar!)",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "A1",
            "example": "Remember to push the door when entering the coffee shop.",
            "examplePt": "Lembre-se de empurrar a porta ao entrar na cafeteria."
      },
      {
            "id": "en_pretend",
            "type": "word",
            "icon": "🎭",
            "term": "pretend",
            "ipa": "/prɪˈtɛnd/",
            "pos": "Verbo",
            "translation": "fingir (não pretender!)",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "B1",
            "example": "The children love to pretend they are superheroes.",
            "examplePt": "As crianças adoram fingir que são super-heróis."
      },
      {
            "id": "en_realize",
            "type": "word",
            "icon": "💡",
            "term": "realize",
            "ipa": "/ˈriː.ə.laɪz/",
            "pos": "Verbo",
            "translation": "perceber / dar-se conta",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "B1",
            "example": "I realized I had forgotten my keys inside the car.",
            "examplePt": "Percebi que tinha esquecido minhas chaves dentro do carro."
      },
      {
        "id": "en_subj_i",
        "type": "word",
        "icon": "👤",
        "term": "I",
        "ipa": "/aɪ/",
        "pos": "Pronome Sujeito",
        "translation": "eu",
        "category": "Pronomes Pessoais (Sujeito)",
        "level": "A1",
        "example": "I learn English every morning.",
        "examplePt": "Eu aprendo inglês toda manhã."
      },
      {
        "id": "en_subj_you",
        "type": "word",
        "icon": "👥",
        "term": "you",
        "ipa": "/juː/",
        "pos": "Pronome Sujeito",
        "translation": "você / vocês",
        "category": "Pronomes Pessoais (Sujeito)",
        "level": "A1",
        "example": "You speak English very clearly.",
        "examplePt": "Você fala inglês muito claramente."
      },
      {
        "id": "en_subj_he",
        "type": "word",
        "icon": "👨",
        "term": "he",
        "ipa": "/hiː/",
        "pos": "Pronome Sujeito",
        "translation": "ele",
        "category": "Pronomes Pessoais (Sujeito)",
        "level": "A1",
        "example": "He works at a technology company.",
        "examplePt": "Ele trabalha em uma empresa de tecnologia."
      },
      {
        "id": "en_subj_she",
        "type": "word",
        "icon": "👩",
        "term": "she",
        "ipa": "/ʃiː/",
        "pos": "Pronome Sujeito",
        "translation": "ela",
        "category": "Pronomes Pessoais (Sujeito)",
        "level": "A1",
        "example": "She loves reading books before bed.",
        "examplePt": "Ela adora ler livros antes de dormir."
      },
      {
        "id": "en_subj_it",
        "type": "word",
        "icon": "📦",
        "term": "it",
        "ipa": "/ɪt/",
        "pos": "Pronome Sujeito",
        "translation": "ele / ela (coisas/animais/clima)",
        "category": "Pronomes Pessoais (Sujeito)",
        "level": "A1",
        "example": "It is raining a lot outside.",
        "examplePt": "Está chovendo muito lá fora."
      },
      {
        "id": "en_subj_we",
        "type": "word",
        "icon": "🤝",
        "term": "we",
        "ipa": "/wiː/",
        "pos": "Pronome Sujeito",
        "translation": "nós",
        "category": "Pronomes Pessoais (Sujeito)",
        "level": "A1",
        "example": "We travel together every summer.",
        "examplePt": "Nós viajamos juntos todo verão."
      },
      {
        "id": "en_subj_they",
        "type": "word",
        "icon": "👨👩👧👦",
        "term": "they",
        "ipa": "/ðeɪ/",
        "pos": "Pronome Sujeito",
        "translation": "eles / elas",
        "category": "Pronomes Pessoais (Sujeito)",
        "level": "A1",
        "example": "They live in a beautiful apartment.",
        "examplePt": "Eles moram em um apartamento bonito."
      },
      {
        "id": "en_obj_me",
        "type": "word",
        "icon": "👤",
        "term": "me",
        "ipa": "/miː/",
        "pos": "Pronome Objeto",
        "translation": "me / mim",
        "category": "Pronomes Objeto",
        "level": "A1",
        "example": "Can you help me with this exercise?",
        "examplePt": "Você pode me ajudar com este exercício?"
      },
      {
        "id": "en_obj_you",
        "type": "word",
        "icon": "👥",
        "term": "you",
        "ipa": "/juː/",
        "pos": "Pronome Objeto",
        "translation": "te / ti / você / vocês",
        "category": "Pronomes Objeto",
        "level": "A1",
        "example": "I will call you tonight.",
        "examplePt": "Eu vou te ligar hoje à noite."
      },
      {
        "id": "en_obj_him",
        "type": "word",
        "icon": "👨",
        "term": "him",
        "ipa": "/hɪm/",
        "pos": "Pronome Objeto",
        "translation": "o / lhe / ele",
        "category": "Pronomes Objeto",
        "level": "A1",
        "example": "I saw him at the supermarket yesterday.",
        "examplePt": "Eu o vi no supermercado ontem."
      },
      {
        "id": "en_obj_her",
        "type": "word",
        "icon": "👩",
        "term": "her",
        "ipa": "/hɜːr/",
        "pos": "Pronome Objeto",
        "translation": "a / lhe / ela",
        "category": "Pronomes Objeto",
        "level": "A1",
        "example": "Give her the book, please.",
        "examplePt": "Entregue o livro para ela, por favor."
      },
      {
        "id": "en_obj_it",
        "type": "word",
        "icon": "📦",
        "term": "it",
        "ipa": "/ɪt/",
        "pos": "Pronome Objeto",
        "translation": "o / a / isto / isso",
        "category": "Pronomes Objeto",
        "level": "A1",
        "example": "I found my phone and picked it up.",
        "examplePt": "Encontrei meu celular e o peguei."
      },
      {
        "id": "en_obj_us",
        "type": "word",
        "icon": "🤝",
        "term": "us",
        "ipa": "/ʌs/",
        "pos": "Pronome Objeto",
        "translation": "nos / nós",
        "category": "Pronomes Objeto",
        "level": "A1",
        "example": "The teacher gave us a lot of homework.",
        "examplePt": "O professor nos deu muita lição de casa."
      },
      {
        "id": "en_obj_them",
        "type": "word",
        "icon": "👨👩👧👦",
        "term": "them",
        "ipa": "/ðɛm/",
        "pos": "Pronome Objeto",
        "translation": "os / as / lhes / eles / elas",
        "category": "Pronomes Objeto",
        "level": "A1",
        "example": "I invited them to my birthday party.",
        "examplePt": "Eu os convidei para minha festa de aniversário."
      },
      {
        "id": "en_poss_adj_my",
        "type": "word",
        "icon": "👤",
        "term": "my",
        "ipa": "/maɪ/",
        "pos": "Adjetivo Possessivo",
        "translation": "meu / minha / meus / minhas",
        "category": "Adjetivos Possessivos",
        "level": "A1",
        "example": "My computer is working very well.",
        "examplePt": "Meu computador está funcionando muito bem."
      },
      {
        "id": "en_poss_adj_your",
        "type": "word",
        "icon": "👥",
        "term": "your",
        "ipa": "/jɔːr/",
        "pos": "Adjetivo Possessivo",
        "translation": "seu / sua / seus / suas",
        "category": "Adjetivos Possessivos",
        "level": "A1",
        "example": "What is your favorite hobby?",
        "examplePt": "Qual é o seu passatempo favorito?"
      },
      {
        "id": "en_poss_adj_his",
        "type": "word",
        "icon": "👨",
        "term": "his",
        "ipa": "/hɪz/",
        "pos": "Adjetivo Possessivo",
        "translation": "dele / seu / sua",
        "category": "Adjetivos Possessivos",
        "level": "A1",
        "example": "His father is a doctor.",
        "examplePt": "O pai dele é médico."
      },
      {
        "id": "en_poss_adj_her",
        "type": "word",
        "icon": "👩",
        "term": "her",
        "ipa": "/hɜːr/",
        "pos": "Adjetivo Possessivo",
        "translation": "dela / seu / sua",
        "category": "Adjetivos Possessivos",
        "level": "A1",
        "example": "Her car is parked in front of the house.",
        "examplePt": "O carro dela está estacionado em frente à casa."
      },
      {
        "id": "en_poss_adj_its",
        "type": "word",
        "icon": "📦",
        "term": "its",
        "ipa": "/ɪts/",
        "pos": "Adjetivo Possessivo",
        "translation": "dele / dela (coisas/animais)",
        "category": "Adjetivos Possessivos",
        "level": "A1",
        "example": "The cat is licking its paws.",
        "examplePt": "O gato está lambendo suas patas."
      },
      {
        "id": "en_poss_adj_our",
        "type": "word",
        "icon": "🤝",
        "term": "our",
        "ipa": "/aʊər/",
        "pos": "Adjetivo Possessivo",
        "translation": "nosso / nossa / nossos / nossas",
        "category": "Adjetivos Possessivos",
        "level": "A1",
        "example": "Our house has a lovely garden.",
        "examplePt": "Nossa casa tem um jardim adorável."
      },
      {
        "id": "en_poss_adj_their",
        "type": "word",
        "icon": "👨👩👧👦",
        "term": "their",
        "ipa": "/ðɛər/",
        "pos": "Adjetivo Possessivo",
        "translation": "deles / delas",
        "category": "Adjetivos Possessivos",
        "level": "A1",
        "example": "Their flight arrives at midnight.",
        "examplePt": "O voo deles chega à meia-noite."
      },
      {
        "id": "en_poss_pron_mine",
        "type": "word",
        "icon": "👤",
        "term": "mine",
        "ipa": "/maɪn/",
        "pos": "Pronome Possessivo",
        "translation": "o meu / a minha / os meus / as minhas",
        "category": "Pronomes Possessivos",
        "level": "A2",
        "example": "This jacket is mine, not yours.",
        "examplePt": "Esta jaqueta é minha, não sua."
      },
      {
        "id": "en_poss_pron_yours",
        "type": "word",
        "icon": "👥",
        "term": "yours",
        "ipa": "/jɔːrz/",
        "pos": "Pronome Possessivo",
        "translation": "o seu / a sua / os seus / as suas",
        "category": "Pronomes Possessivos",
        "level": "A2",
        "example": "Is that red backpack yours?",
        "examplePt": "Aquela mochila vermelha é sua?"
      },
      {
        "id": "en_poss_pron_his",
        "type": "word",
        "icon": "👨",
        "term": "his",
        "ipa": "/hɪz/",
        "pos": "Pronome Possessivo",
        "translation": "o dele / a dele",
        "category": "Pronomes Possessivos",
        "level": "A2",
        "example": "My car is blue, and his is silver.",
        "examplePt": "Meu carro é azul, e o dele é prata."
      },
      {
        "id": "en_poss_pron_hers",
        "type": "word",
        "icon": "👩",
        "term": "hers",
        "ipa": "/hɜːrz/",
        "pos": "Pronome Possessivo",
        "translation": "o dela / a dela",
        "category": "Pronomes Possessivos",
        "level": "A2",
        "example": "The keys on the table are hers.",
        "examplePt": "As chaves na mesa são dela."
      },
      {
        "id": "en_poss_pron_ours",
        "type": "word",
        "icon": "🤝",
        "term": "ours",
        "ipa": "/aʊərz/",
        "pos": "Pronome Possessivo",
        "translation": "o nosso / a nossa / os nossos / as nossas",
        "category": "Pronomes Possessivos",
        "level": "A2",
        "example": "Their house is large, but ours is cozy.",
        "examplePt": "A casa deles é grande, mas a nossa é aconchegante."
      },
      {
        "id": "en_poss_pron_theirs",
        "type": "word",
        "icon": "👨👩👧👦",
        "term": "theirs",
        "ipa": "/ðɛərz/",
        "pos": "Pronome Possessivo",
        "translation": "o deles / a delas",
        "category": "Pronomes Possessivos",
        "level": "A2",
        "example": "The decision is completely theirs.",
        "examplePt": "A decisão é completamente deles."
      }
    ],
      es: [
      {
            "id": "es_manzana",
            "type": "word",
            "icon": "🍎",
            "term": "la manzana",
            "ipa": "/la manˈθana/",
            "pos": "Substantivo",
            "translation": "a maçã",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "Como una manzana fresca todas las mañanas.",
            "examplePt": "Como uma maçã fresca todas as manhãs."
      },
      {
            "id": "es_pan",
            "type": "word",
            "icon": "🍞",
            "term": "el pan",
            "ipa": "/el pan/",
            "pos": "Substantivo",
            "translation": "o pão",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "¿Compraste pan caliente en la panadería?",
            "examplePt": "Você comprou pão quentinho na padaria?"
      },
      {
            "id": "es_cafe",
            "type": "word",
            "icon": "☕",
            "term": "el café",
            "ipa": "/el kaˈfe/",
            "pos": "Substantivo",
            "translation": "o café",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "Me gustaría un café con leche templada, por favor.",
            "examplePt": "Gostaria de um café com leite morno, por favor."
      },
      {
            "id": "es_agua",
            "type": "word",
            "icon": "💧",
            "term": "el agua",
            "ipa": "/el ˈaɣwa/",
            "pos": "Substantivo",
            "translation": "a água (substantivo feminino com artigo 'el')",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "¿Me traes un vaso de agua fresca, por favor?",
            "examplePt": "Você me traz um copo de água fresca, por favor?"
      },
      {
            "id": "es_la_cuenta_por_favor",
            "type": "chunk",
            "icon": "🧾",
            "term": "la cuenta, por favor",
            "ipa": "/la ˈkwenta por faˈβor/",
            "pos": "Expressão",
            "translation": "a conta, por favor",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "¿Nos cobras? La cuenta, por favor.",
            "examplePt": "Pode nos cobrar? A conta, por favor."
      },
      {
            "id": "es_una_cana",
            "type": "chunk",
            "icon": "🍺",
            "term": "una caña",
            "ipa": "/ˈuna ˈkaɲa/",
            "pos": "Expressão",
            "translation": "um chope (cerveja tirada de pressão)",
            "category": "Alimentos & Bebidas",
            "level": "A1",
            "example": "Camarero, ponme una caña bien fría y unas tapas.",
            "examplePt": "Garçom, me vê um chope bem gelado e uns petiscos."
      },
      {
            "id": "es_dejar_propina",
            "type": "chunk",
            "icon": "🪙",
            "term": "dejar propina",
            "ipa": "/deˈxar proˈpina/",
            "pos": "Expressão",
            "translation": "deixar gorjeta",
            "category": "Alimentos & Bebidas",
            "level": "A2",
            "example": "El servicio fue excelente, así que vamos a dejar propina.",
            "examplePt": "O atendimento foi excelente, então vamos deixar gorjeta."
      },
      {
            "id": "es_el_menu_del_dia",
            "type": "chunk",
            "icon": "🍽️",
            "term": "el menú del día",
            "ipa": "/el meˈnu ðel ˈdi.a/",
            "pos": "Expressão",
            "translation": "prato executivo do dia a preço fixo",
            "category": "Alimentos & Bebidas",
            "level": "A2",
            "example": "¿Qué incluye el primer plato del menú del día hoy?",
            "examplePt": "O que inclui o primeiro prato do menu do dia hoje?"
      },
      {
            "id": "es_aeropuerto",
            "type": "word",
            "icon": "✈️",
            "term": "el aeropuerto",
            "ipa": "/el aeɾoˈpweɾto/",
            "pos": "Substantivo",
            "translation": "o aeroporto",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "El taxi nos llevará directamente al aeropuerto.",
            "examplePt": "O táxi nos levará diretamente ao aeroporto."
      },
      {
            "id": "es_maleta",
            "type": "word",
            "icon": "🧳",
            "term": "la maleta",
            "ipa": "/la maˈleta/",
            "pos": "Substantivo",
            "translation": "a mala",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "Ya tengo la maleta lista para viajar a Barcelona.",
            "examplePt": "Já estou com a mala pronta para viajar a Barcelona."
      },
      {
            "id": "es_billete",
            "type": "word",
            "icon": "🎫",
            "term": "el billete",
            "ipa": "/el biˈʎete/",
            "pos": "Substantivo",
            "translation": "a passagem / bilhete",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "Quisiera un billete de ida y vuelta para Sevilla.",
            "examplePt": "Queria uma passagem de ida e volta para Sevilha."
      },
      {
            "id": "es_parada",
            "type": "word",
            "icon": "🚏",
            "term": "la parada",
            "ipa": "/la paˈɾaða/",
            "pos": "Substantivo",
            "translation": "o ponto de ônibus ou parada",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "¿Dónde está la parada de autobús más cercana?",
            "examplePt": "Onde fica o ponto de ônibus mais próximo?"
      },
      {
            "id": "es_tarjeta_de_embarque",
            "type": "chunk",
            "icon": "🎫",
            "term": "tarjeta de embarque",
            "ipa": "/taɾˈxeta ðe emˈbaɾke/",
            "pos": "Expressão",
            "translation": "cartão de embarque",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "Descargue su tarjeta de embarque en el teléfono móvil.",
            "examplePt": "Baixe seu cartão de embarque no celular."
      },
      {
            "id": "es_equipaje_de_mano",
            "type": "chunk",
            "icon": "🎒",
            "term": "equipaje de mano",
            "ipa": "/ekiˈpaxe ðe ˈmano/",
            "pos": "Expressão",
            "translation": "bagagem de mão",
            "category": "Viagem & Cidade",
            "level": "A2",
            "example": "Solo llevo una mochila pequeña como equipaje de mano.",
            "examplePt": "Levo apenas uma mochila pequena como bagagem de mão."
      },
      {
            "id": "es_girar_a_la_derecha",
            "type": "chunk",
            "icon": "➡️",
            "term": "girar a la derecha",
            "ipa": "/xiˈɾaɾ a la ðeˈɾetʃa/",
            "pos": "Expressão",
            "translation": "virar à direita",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "Siga recto y luego gire a la derecha en la farmacia.",
            "examplePt": "Siga em frente e depois vire à direita na farmácia."
      },
      {
            "id": "es_seguir_recto",
            "type": "chunk",
            "icon": "⬆️",
            "term": "seguir recto",
            "ipa": "/seˈɣiɾ ˈrekto/",
            "pos": "Expressão",
            "translation": "seguir reto / seguir em frente",
            "category": "Viagem & Cidade",
            "level": "A1",
            "example": "Para llegar a la catedral debe seguir todo recto.",
            "examplePt": "Para chegar à catedral deve seguir todo em frente."
      },
      {
            "id": "es_reunion",
            "type": "word",
            "icon": "💼",
            "term": "la reunión",
            "ipa": "/la rewˈnjon/",
            "pos": "Substantivo",
            "translation": "a reunião",
            "category": "Trabalho & Rotina",
            "level": "A2",
            "example": "Tenemos una reunión de equipo todos los lunes.",
            "examplePt": "Temos uma reunião de equipe todas as segundas."
      },
      {
            "id": "es_plazo",
            "type": "word",
            "icon": "⏳",
            "term": "el plazo",
            "ipa": "/el ˈplaθo/",
            "pos": "Substantivo",
            "translation": "o prazo de entrega",
            "category": "Trabalho & Rotina",
            "level": "B1",
            "example": "El plazo para entregar el informe vence mañana.",
            "examplePt": "O prazo para entregar o relatório vence amanhã."
      },
      {
            "id": "es_cumplir_el_plazo",
            "type": "chunk",
            "icon": "🎯",
            "term": "cumplir el plazo",
            "ipa": "/kumˈpliɾ el ˈplaθo/",
            "pos": "Expressão",
            "translation": "cumprir o prazo",
            "category": "Trabalho & Rotina",
            "level": "B1",
            "example": "Trabajamos duro para cumplir el plazo acordado.",
            "examplePt": "Trabalhamos duro para cumprir o prazo combinado."
      },
      {
            "id": "es_teletrabajar",
            "type": "word",
            "icon": "💻",
            "term": "teletrabajar",
            "ipa": "/teletɾaβaˈxaɾ/",
            "pos": "Verbo",
            "translation": "fazer home office / trabalhar remoto",
            "category": "Trabalho & Rotina",
            "level": "A2",
            "example": "En mi empresa podemos teletrabajar dos días por semana.",
            "examplePt": "Na minha empresa podemos fazer home office dois dias por semana."
      },
      {
            "id": "es_horas_extras",
            "type": "chunk",
            "icon": "⏰",
            "term": "hacer horas extras",
            "ipa": "/aˈseɾ ˈoɾas ˈekstɾas/",
            "pos": "Expressão",
            "translation": "fazer hora extra",
            "category": "Trabalho & Rotina",
            "level": "A2",
            "example": "Tuve que hacer horas extras para terminar el proyecto.",
            "examplePt": "Tive que fazer horas extras para terminar o projeto."
      },
      {
            "id": "es_pedir_cita",
            "type": "chunk",
            "icon": "🗓️",
            "term": "pedir cita",
            "ipa": "/peˈðiɾ ˈθita/",
            "pos": "Expressão",
            "translation": "marcar horário / consulta",
            "category": "Trabalho & Rotina",
            "level": "A2",
            "example": "Necesito pedir cita previa con el médico.",
            "examplePt": "Preciso agendar uma consulta com o médico."
      },
      {
            "id": "es_madrugar",
            "type": "word",
            "icon": "🌅",
            "term": "madrugar",
            "ipa": "/maðɾuˈɣaɾ/",
            "pos": "Verbo",
            "translation": "acordar bem cedo / madrugar",
            "category": "Trabalho & Rotina",
            "level": "A2",
            "example": "Mañana tengo que madrugar para tomar el primer tren.",
            "examplePt": "Amanhã tenho que madrugar para pegar o primeiro trem."
      },
      {
            "id": "es_llave",
            "type": "word",
            "icon": "🔑",
            "term": "la llave",
            "ipa": "/la ˈʎaβe/",
            "pos": "Substantivo",
            "translation": "a chave",
            "category": "Cotidiano & Objetos",
            "level": "A1",
            "example": "¿Dónde dejaste la llave de la habitación?",
            "examplePt": "Onde você deixou a chave do quarto?"
      },
      {
            "id": "es_cartera",
            "type": "word",
            "icon": "👛",
            "term": "la cartera",
            "ipa": "/la kaɾˈteɾa/",
            "pos": "Substantivo",
            "translation": "a carteira",
            "category": "Cotidiano & Objetos",
            "level": "A1",
            "example": "No llevo efectivo en mi cartera, solo tarjetas.",
            "examplePt": "Não levo dinheiro vivo na minha carteira, só cartões."
      },
      {
            "id": "es_echarse_la_siesta",
            "type": "chunk",
            "icon": "😴",
            "term": "echarse una siesta",
            "ipa": "/eˈtʃaɾse ˈuna ˈsjesta/",
            "pos": "Expressão",
            "translation": "tirar um cochilo / fazer a sesta",
            "category": "Cotidiano & Objetos",
            "level": "A2",
            "example": "Los domingos me gusta echarme una siesta después de comer.",
            "examplePt": "Aos domingos gosto de tirar um cochilo depois do almoço."
      },
      {
            "id": "es_echar_de_menos",
            "type": "chunk",
            "icon": "💭",
            "term": "echar de menos",
            "ipa": "/eˈtʃaɾ ðe ˈmenos/",
            "pos": "Expressão",
            "translation": "sentir saudades / sentir falta",
            "category": "Cotidiano & Objetos",
            "level": "A2",
            "example": "Echo mucho de menos a mi familia cuando viajo.",
            "examplePt": "Sinto muitas saudades da minha família quando viajo."
      },
      {
            "id": "es_valer_la_pena",
            "type": "chunk",
            "icon": "✨",
            "term": "valer la pena",
            "ipa": "/baˈleɾ la ˈpena/",
            "pos": "Expressão",
            "translation": "valer a pena",
            "category": "Cotidiano & Objetos",
            "level": "A2",
            "example": "El viaje fue largo, pero conocer la Alhambra valió la pena.",
            "examplePt": "A viagem foi longa, mas conhecer o Alhambra valeu a pena."
      },
      {
            "id": "es_llegar",
            "type": "word",
            "icon": "🛬",
            "term": "llegar",
            "ipa": "/ʎeˈɣaɾ/",
            "pos": "Verbo",
            "translation": "chegar",
            "category": "Ações Essenciais / Verbos",
            "level": "A1",
            "example": "El tren va a llegar a la estación en cinco minutos.",
            "examplePt": "O trem vai chegar na estação em cinco minutos."
      },
      {
            "id": "es_elegir",
            "type": "word",
            "icon": "🎯",
            "term": "elegir",
            "ipa": "/eleˈxiɾ/",
            "pos": "Verbo",
            "translation": "escolher / eleger",
            "category": "Ações Essenciais / Verbos",
            "level": "A2",
            "example": "Es difícil elegir entre tantas opciones deliciosas.",
            "examplePt": "É difícil escolher entre tantas opções deliciosas."
      },
      {
            "id": "es_por_supuesto",
            "type": "chunk",
            "icon": "👍",
            "term": "por supuesto",
            "ipa": "/por suˈpwesto/",
            "pos": "Expressão",
            "translation": "com certeza / claro que sim",
            "category": "Ações Essenciais / Verbos",
            "level": "A1",
            "example": "—¿Vienes a la fiesta con nosotros? —¡Por supuesto!",
            "examplePt": "— Você vem à festa conosco? — Com certeza!"
      },
      {
            "id": "es_sin_embargo",
            "type": "chunk",
            "icon": "⚖️",
            "term": "sin embargo",
            "ipa": "/sin emˈbaɾɣo/",
            "pos": "Expressão",
            "translation": "no entanto / porém",
            "category": "Ações Essenciais / Verbos",
            "level": "B1",
            "example": "Estudió mucho; sin embargo, el examen fue muy complejo.",
            "examplePt": "Estudou muito; no entanto, o exame foi muito complexo."
      },
      {
            "id": "es_darse_cuenta",
            "type": "chunk",
            "icon": "💡",
            "term": "darse cuenta de",
            "ipa": "/ˈdaɾse ˈkwenta ðe/",
            "pos": "Expressão",
            "translation": "perceber / dar-se conta",
            "category": "Ações Essenciais / Verbos",
            "level": "B1",
            "example": "Me di cuenta de que había olvidado el cargador del móvil.",
            "examplePt": "Percebi que tinha esquecido o carregador do celular."
      },
      {
            "id": "es_a_lo_mejor",
            "type": "chunk",
            "icon": "🎲",
            "term": "a lo mejor",
            "ipa": "/a lo meˈxoɾ/",
            "pos": "Expressão",
            "translation": "talvez / quem sabe (+ indicativo)",
            "category": "Ações Essenciais / Verbos",
            "level": "A2",
            "example": "A lo mejor vamos a la playa si hace buen tiempo.",
            "examplePt": "Talvez a gente vá à praia se fizer tempo bom."
      },
      {
            "id": "es_embarazada",
            "type": "word",
            "icon": "🤰",
            "term": "embarazada",
            "ipa": "/embaɾaˈθaða/",
            "pos": "Adjetivo",
            "translation": "grávida (não embaraçada!)",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "A2",
            "example": "Mi hermana mayor está embarazada y espera una niña.",
            "examplePt": "Minha irmã mais velha está grávida e espera uma menina."
      },
      {
            "id": "es_exito",
            "type": "word",
            "icon": "🏆",
            "term": "el éxito",
            "ipa": "/el ˈeɡzito/",
            "pos": "Substantivo",
            "translation": "o sucesso (não a saída!)",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "A2",
            "example": "La presentación del proyecto fue un gran éxito.",
            "examplePt": "A apresentação do projeto foi um grande sucesso."
      },
      {
            "id": "es_largo",
            "type": "word",
            "icon": "📏",
            "term": "largo",
            "ipa": "/ˈlaɾɣo/",
            "pos": "Adjetivo",
            "translation": "comprido / longo (não largo!)",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "A1",
            "example": "Ella tiene el pelo muy largo y castaño.",
            "examplePt": "Ela tem o cabelo bem comprido e castanho."
      },
      {
            "id": "es_apellido",
            "type": "word",
            "icon": "🏷️",
            "term": "el apellido",
            "ipa": "/el apeˈʎiðo/",
            "pos": "Substantivo",
            "translation": "o sobrenome (não apelido!)",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "A1",
            "example": "¿Cómo se escribe tu primer apellido familiar?",
            "examplePt": "Como se escreve o seu primeiro sobrenome da família?"
      },
      {
            "id": "es_vaso",
            "type": "word",
            "icon": "🥛",
            "term": "el vaso",
            "ipa": "/el ˈbaso/",
            "pos": "Substantivo",
            "translation": "o copo (não vaso de flor!)",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "A1",
            "example": "Sirve un vaso de zumo de naranja, por favor.",
            "examplePt": "Sirva um copo de suco de laranja, por favor."
      },
      {
            "id": "es_sobremesa",
            "type": "word",
            "icon": "🗣️",
            "term": "la sobremesa",
            "ipa": "/la soβɾeˈmesa/",
            "pos": "Substantivo",
            "translation": "conversa pós-refeição à mesa (não doce!)",
            "category": "Falsos Cognatos / Pegadinhas",
            "level": "B1",
            "example": "Pasamos dos horas haciendo sobremesa los domingos.",
            "examplePt": "Passamos duas horas conversando à mesa aos domingos."
      }
    ]
  };

  global.VOCABULARY_DATA = VOCABULARY_DATA;
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = VOCABULARY_DATA;
  }
})(typeof window !== 'undefined' ? window : (typeof global !== 'undefined' ? global : globalThis));
